networks:
  monitoring_network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/config.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - "monitoring_network"

  grafana:
    image: grafana/grafana:11.6.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    networks:
      - "monitoring_network"