name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: make api-codegen
      - run: make sqlc-codegen
      - run: make lint
        env:
          CI: true
      - run: npm run lint
        env:
          CI: true
      - run: npm run build
        env:
          CI: true